# - name: configure "{{ component }}"
#   become: yes
#   hosts: "{{ component }}"
#   roles: # this will automatically load a folder called roles in current working directory.
#   - "{{ component }}"

- name: "configure mongodb
  become: yes
  hosts: mongodb
  roles: # this will automatically load a folder called roles in current working directory.
  - mongodb